---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If **Elise** doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning. \
    \
    Elise consistently asks helpful questions and provides comments on the class Discord, and their code consistently looks well formatted and produces creative results.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.\
    \
    Some of the final content in the class (e.g. function writing, using double curly brackets, etc.) was more difficult. Not having any real computer science background, it was easy to get lost in the weeds of terminology that probably would have been clarified in an intro CS class. I didn't fare too badly, but I also don't feel like I was *all the way* there in terms of understanding.

3.  What was the easiest part of the class for you? Explain why.\
    \
    Most of my previous experience in R was using basic tidy functions for cleaning data, as well as generating figures in ggplot. Even new skills I learned in those categories felt straightforward to me.

4.  What part of the class surprised or interested you the most? Explain why.\
    \
    The stringr and map functions have already proven to be incredibly useful to me in projects beyond this class. I hadn't thought much of them as we were learning them, but they've quickly become indispensable tools, especially for cleaning datasheets that have been generated by several different collaborators aligned to the same variable names.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.\
    \
